// This is an auto generated file by createTxnTypes.py

#include <stdint.h>
#include "ardor.h"

const txnType TXN_TYPES[] = {{0x00fc, "Issue Exchange Order", 4},
                             {0x01fc, "Cancel Exchange Order", 0},
                             {0x00fd, "Lease Forging Balance", 0},
                             {0x00fe, "Make Payment", 0},
                             {0x00ff, "Child Chain Block", 0},
                             {0x0000, "Make Payment", 0},
                             {0x0001, "Send Message", 0},
                             {0x0002, "Issue Asset", 0},
                             {0x0102, "Transfer Asset", 7},
                             {0x0202, "Place Ask Order", 5},
                             {0x0302, "Place Bid Order", 5},
                             {0x0402, "Cancel Ask Order", 0},
                             {0x0502, "Cancel Bid Order", 0},
                             {0x0602, "Pay Dividends", 0},
                             {0x0702, "Delete Asset Shares", 0},
                             {0x0802, "Increase Asset Shares", 0},
                             {0x0902, "Set Asset Control", 0},
                             {0x0a02, "Set Asset Property", 0},
                             {0x0b02, "Delete Asset Property", 0},
                             {0x0003, "Marketplace Listing", 0},
                             {0x0103, "Marketplace Delisting", 0},
                             {0x0203, "Marketplace Price Change", 0},
                             {0x0303, "Marketplace Quantity Change", 0},
                             {0x0403, "Marketplace Purchase", 0},
                             {0x0503, "Marketplace Delivery", 0},
                             {0x0603, "Marketplace Feedback", 0},
                             {0x0703, "Marketplace Refund", 0},
                             {0x0004, "Set Phasing Only", 0},
                             {0x0005, "Issue Currency", 0},
                             {0x0105, "Increase Currency Reserve", 0},
                             {0x0205, "Claim Currency Reserve", 0},
                             {0x0305, "Transfer Currency", 0},
                             {0x0405, "Publish Currency Exchange Offer", 0},
                             {0x0505, "Buy Currency", 0},
                             {0x0605, "Sell Currency", 0},
                             {0x0705, "Mint Currency", 0},
                             {0x0805, "Delete Currency", 0},
                             {0x0006, "Data Cloud Upload", 0},
                             {0x0007, "Create Shuffling", 0},
                             {0x0107, "Shuffling Registration", 0},
                             {0x0207, "Shuffling Processing", 0},
                             {0x0307, "Shuffling Recipients", 0},
                             {0x0407, "Shuffling Verification", 0},
                             {0x0507, "Cancel Shuffling", 0},
                             {0x0008, "Set Alias", 0},
                             {0x0108, "Sell Alias", 0},
                             {0x0208, "Buy Alias", 0},
                             {0x0308, "Delete Alias", 0},
                             {0x0009, "Create Poll", 0},
                             {0x0109, "Cast Vote", 0},
                             {0x0209, "Cast Phasing Vote", 0},
                             {0x000a, "Set Account Info", 0},
                             {0x010a, "Set Account Property", 0},
                             {0x020a, "Delete Account Property", 0},
                             {0x000b, "Issue Exchange Order", 4},
                             {0x010b, "Cancel Exchange Order", 0},
                             {0x000c, "Set Contract Reference", 0},
                             {0x010c, "Delete Contract Reference", 0},
                             {0x000d, "Add Chain Permission", 0},
                             {0x010d, "Remove Chain Permission", 0}};

const uint8_t LEN_TXN_TYPES = 60;
